1666409524960	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1666409524962	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1666410517997	Sync.RemoteTabs	INFO	Generating tab list with filter
1666410517997	Sync.RemoteTabs	INFO	Final tab list has 0 clients with 0 tabs.
1666413124961	Sync.Service	DEBUG	User-Agent: Firefox/105.0.2 (Linux x86_64) FxSync/1.107.0.20221005092643.desktop
1666413124961	Sync.Service	INFO	Starting sync at 2022-10-22 12:32:04 in browser session 3X7Rvx6kaQCD
1666413124961	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1666413124963	Sync.Status	INFO	Resetting Status.
1666413124963	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1666413124963	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1666413124963	FirefoxAccounts	DEBUG	getOAuthToken enter
1666413124964	FirefoxAccounts	TRACE	getCachedToken returning cached token
1666413124964	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1666413124964	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1666413124965	Sync.SyncAuthManager	INFO	Getting sync key
1666413124965	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1666413124965	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1666413124965	FirefoxAccounts	DEBUG	getOAuthToken enter
1666413124965	FirefoxAccounts	TRACE	getCachedToken returning cached token
1666413124965	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1666413124965	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1666413124965	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1666413148575	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398919 - NS_ERROR_NET_INTERRUPT
1666413148575	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1666413148576	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1666413148576	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1666413148576	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1666413163882	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398862 - NS_ERROR_NET_TIMEOUT
1666413163882	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 489\"  data: no]"}
1666413163883	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 489\"  data: no]"}
1666413181728	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/198175302/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1666413181729	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1666413181729	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1666413181729	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1666413181729	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1666413181730	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1666413181734	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
